name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
setup:
    runs-on: ubuntu-latest
    steps:
      - run: ./deploy.sh
    - name: vuepress-deploy
      uses: ly-yuan/blog@main
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: ly-yuan/blog
        TARGET_BRANCH: main
        BUILD_DIR: docs/.vuepress/dist